### PR TITLE
Saving full .parquet file

### LINKED ISSUE #14: Panic on sending results over gRPC to normalizer
Have to do with gRPC message size, most probably a twin on bblfsh/server#58

```
INFO[07-13|15:18:03] Done. All files parsed                   repo=015d36fc-8de9-8fab-e5a9-0c11bdf41e2b success=31 fail=0 skipped=13
INFO[07-13|15:18:03] Done. All files in all repositories parsed repositories=18 files=3722

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16f3737]

goroutine 51 [running]:
github.com/src-d/berserker/extractor.(*RepositoryData).ProtoSize(0x0, 0x2)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/generated.pb.go:418 +0x37
github.com/src-d/berserker/extractor.(*Service_GetRepositoriesDataResponse).ProtoSize(0xc4209ec280, 0x177e160)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/generated.pb.go:464 +0x5b
github.com/src-d/berserker/extractor.(*Service_GetRepositoriesDataResponse).Marshal(0xc4209ec280, 0x219fa80, 0xc4209ec280, 0x3588f58, 0xc4209ec280, 0x1)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/generated.pb.go:337 +0x2f
github.com/src-d/berserker/extractor/vendor/github.com/golang/protobuf/proto.(*Buffer).Marshal(0xc4209f4758, 0x219fa80, 0xc4209ec280, 0xc43019dea0, 0x0)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/github.com/golang/protobuf/proto/encode.go:264 +0x7a
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.protoCodec.marshal(0x1846c60, 0xc4209ec280, 0xc4209f4750, 0xc42d3f57f8, 0x10862c2, 0xed0f96a0b, 0x20f0983e, 0x21ee0e0)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/codec.go:78 +0xe8
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.protoCodec.Marshal(0x1846c60, 0xc4209ec280, 0xd, 0x283f5484, 0x21ee0e0, 0xc42d3f5868, 0x106e954)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/codec.go:88 +0x73
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*protoCodec).Marshal(0x220a7a0, 0x1846c60, 0xc4209ec280, 0x13bd860, 0xc420a50054, 0xed0f96a0b, 0x20f0983e, 0x21ee0e0)
	<autogenerated>:35 +0x59
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.encode(0x21a1600, 0x220a7a0, 0x1846c60, 0xc4209ec280, 0x0, 0x0, 0x0, 0x0, 0xed0f96a0b, 0x100000020f0983e, ...)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/rpc_util.go:316 +0x2f9
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*Server).sendResponse(0xc4209f8000, 0x21a5260, 0xc420a42000, 0xc420a4e000, 0x1846c60, 0xc4209ec280, 0x0, 0x0, 0xc43019de90, 0x0, ...)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/server.go:665 +0xb5
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4209f8000, 0x21a5260, 0xc420a42000, 0xc420a4e000, 0xc4209e82d0, 0x21dcc60, 0xc4209dc4e0, 0x0, 0x0)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/server.go:821 +0x12c9
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4209f8000, 0x21a5260, 0xc420a42000, 0xc420a4e000, 0xc4209dc4e0)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/server.go:997 +0x15a6
github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420a0c090, 0xc4209f8000, 0x21a5260, 0xc420a42000, 0xc420a4e000)
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/server.go:561 +0xa9
created by github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/alex/go/src/github.com/src-d/berserker/extractor/vendor/google.golang.org/grpc/server.go:562 +0xa1
```

### PR DESCRIPTION
**Pull request by bzz**
- [x] pass CLI arg `--limit=N`to limit number of processed repos to aid debugging
  - [x] increase Berserker internal gRPC max msg size limit to 100mb
  - [x] increase Berserker -> Bblfsh server gRPC max msg size limit to 100mb
  - [x] add repoURL to .parquet file
  - [x] fixes #14 

Set of .parquet files was produced, using these changes.

## Test Plan

```
#with latest local build of bblfsh-server
docker run -e 'BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f"' --privileged -p 9432:9432 --name bblfsh bblfsh/server:dev-6bc7fd7 --max-message-size 100

cd extractor
go build -o extractor-server  ./server/*.go
./extractor-server -profiler -limit 10

cd normalizer
./sbt run
```

Instructions in #16 could be used to verify resulting format: UAST pb format

### CODE REVIEW

**Comment by bzz** [comment]
\cc @smola for a review

File: .gitignore [hunk 1]
```diff
@@ -5,4 +5,5 @@ extractor/vendor
 .idea
 #*
 .DS_Store
-*.iml
\ No newline at end of file
+*.iml
+*~
```
Comment (ajnavarro) [inline .gitignore:9]: What does this mean?

File: extractor/service.go [hunk 2]
```diff
@@ -45,109 +55,129 @@ func (s *Service) GetRepositoryData(r *Request) (*RepositoryData, error) {
...
-				skpFiles++
-				return nil
-			} //TODO(bzz): filter binaries like .apk and .jar
+		fLang := enry.GetLanguage(f.Name, []byte(fContent))
+		if err != nil {
+			log.Warn("Failed to detect language", "file", f.Name, "err", err)
+			errFiles++
+			return nil
+		}
+		//log.Debug(fmt.Sprintf("\t%-9s blob %s    %s", fLang, f.Hash, f.Name))
```
Comment (ajnavarro) [inline extractor/service.go]: remove commented code.

File: extractor/service.go [hunk 3]
```diff
@@ -229,16 +260,30 @@ func findAllFetchedReposWithRef(refText string) map[model.SHA1]string {
...
 		}
 
-		repos[masterRef.Init] = repo.ID.String()
+		repos[masterRef.Init] = repo
 	}
 	return repos
 }
 
+// If N=0, get total number of fetched respoitories from DB. Use N otherwise.
+func allOrN(n uint64) uint64 {
```
Comment (ajnavarro) [inline extractor/service.go:274]: Instead of do this, you can add a Limit into the query if `n <=0`

**Review by ajnavarro — APPROVED** [review]

**Review by ajnavarro — CHANGES_REQUESTED** [review]
check comments above.

File: .gitignore (hunk 1 above)
Comment (smola) [reply .gitignore:9]: It's just for temporary files created by some editors that use the `~` suffix.

**Review by smola — APPROVED** [review]
Check @ajnavarro comments.

File: .gitignore (hunk 1 above)
Comment (bzz) [reply .gitignore:9]: Good question :)
This means that people who are using Emacs not going to see un-saved-but-edited files in git

File: extractor/service.go (hunk 3 above)
Comment (bzz) [reply extractor/service.go:274]: This may be a bit miss-leading, but the reason for this code is - a convenience for debugging. I found that it's very convenient to know exact `N` and print it to the logs (before iterating over anything).

That is why there is query to DB here, in case when user did not provide us with desired limit.

**Comment by bzz** [comment]
@ajnavarro comments addressed in fe90798

Please let me know if there is anything else that stops from merging this guy.

**Review by ajnavarro — APPROVED** [review]
